config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :mailer => 'users/mailer'
  } 

  devise_scope :user do
    get 'users/:id/posts' => 'users/registrations#user_posts', as: 'users_posts'
    get 'users/:id/liked_aquaria' => 'users/registrations#liked_aquaria', as: 'users_liked_aquaria'
    post 'users/guest_sign_in' => 'users/sessions#new_guest'
    get 'sign_up' => 'users/registrations#new'
    get 'log_in' => 'users/sessions#new'
    get 'log_out' => 'users/sessions#destroy'
    get 'users/:id/detail' => 'users/registrations#detail', as: 'detail'
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  root 'home#top'
  get '/' => 'home#top'
  resources :aquaria do
    collection do
      get 'search'
    end
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :maps, only: :index
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/aquaria_controller.rb
class AquariaController < ApplicationController
  before_action :authenticate_user!
  before_action :set_q, only: [:index, :search]

  def index
    @aquarium = Aquarium.new
    @aquaria = Aquarium.all.order(created_at: :desc).page(params[:page]).per(15)
    @like = Like.new
  end

  def show
    @aquarium = Aquarium.find(params[:id])
    @like = Like.new
    @liked_users = @aquarium.liked_users
    @comment = Comment.new
    @comments = @aquarium.comments.all.order(created_at: :desc)
  end

  def new
    @aquarium = Aquarium.new
  end

  def create
    @aquarium = Aquarium.new(aquarium_params)

    respond_to do |format|
      if @aquarium.save
        flash[:notice] = "アクアリウムを投稿しました"
        format.html { redirect_to @aquarium }
        format.js { render js: "window.location = '#{aquarium_path(@aquarium)}' " }
      else
        format.html { redirect_to @aquarium }
        format.js { @status = "fail" }
      end
    end
  end

  def edit
    @aquarium = Aquarium.find(params[:id])
  end

  def update
    @aquarium = Aquarium.find(params[:id])

    respond_to do |format|
      if @aquarium.update(aquarium_params)
        flash[:notice] = "投稿を更新しました"
        format.html { redirect_to @aquarium }
        format.js { render js: "window.location = '#{aquarium_path(@aquarium)}' " }
      else
        format.html { redirect_to @aquarium }
        format.js { @status = "fail" }
      end
    end
  end

  def destroy
    @aquarium = Aquarium.find(params[:id])
    @aquarium.destroy
    flash[:notice] = "投稿を削除しました"
    redirect_to aquaria_path
  end

  def search
    @results = @q.result.order(created_at: :desc).page(params[:page]).per(24)
    @count = @results.count
  end

  private

  def set_q
    @q = Aquarium.ransack(params[:q])
  end

  def aquarium_params
    params.require(:aquarium).permit(:aquarium_introduction, :aquarium_image, :user_id)
  end
end

app/views/aquaria/_edit.html.erb
<div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="editModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-inner">
        <div class="close-modal">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">投稿編集</h5>
        </div>
        <%= form_for aquarium do |f| %>
          <div class="modal-body">
            <div class="mb-3">
              <%= f.label :aquarium_introduction, "投稿内容", class: "col-form-label", for: "message-text" %>
              <%= f.text_area :aquarium_introduction, class: "form-control", id: "message-text", size: "30x5" %>
            </div>
            <div class="mb-3">
              <%= f.label :aquarium_image, "画像", class: "col-form-label" %>
              <%= f.file_field :aquarium_image, class: "form-control" %>
            </div>
              <%= f.hidden_field :user_id, value: current_user.id %>
          </div> 
          <div class="modal-footer">
          <%= f.submit "更新する", class: "btn btn-primary mb-3" %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/aquaria/_navbar.html.erb
<div class="col-lg-2 sidebar bg-color p-4 d-none d-lg-block shadow p-3 mb-5 bg-white rounded">
  <ul class="nav flex-column aquaria-nav-pc">
    <li class="nav-item">
      <%= link_to "投稿一覧", aquaria_path, class: "nav-link active" %>
    </li>
    <li class="nav-item">
      <%= link_to "新規投稿", new_aquarium_path, class: "nav-link", remote: true %>
    </li>
    <li class="nav-item ">
      <%= render 'search_field', q: @q, url: search_aquaria_path %>
    </li>
  </ul>
</div>
<div class="col-lg-2 bg-color d-lg-none nav-sp-frame shadow p-3 mb-5 bg-white rounded">
  <ul class="nav" id="nav-sp">
    <li class="nav-item">
      <%= link_to "投稿一覧", aquaria_path, class: "nav-link active" %>
    </li>
    <li class="nav-item">
      <%= link_to "新規投稿", new_aquarium_path, class: "nav-link", remote: true %>
    </li>
    <li class="nav-item search-li">
      <%= search_form_for @q, url: search_aquaria_path do |f| %>
        <div class="search-field">
          <%= f.search_field :aquarium_introduction_cont, class: "form-control", placeholder: '投稿検索' %>
          <i class="fas fa-search"></i>
        </div>
        <%= f.submit class: "d-none" %>
      <% end %>
    </li>
  </ul>
</div>

app/views/aquaria/_new_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-inner">
      <div class="close-modal">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id="new-modal-error"></div>
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">新規投稿</h5>
      </div>
      <%= form_with model: @aquarium, remote: true do |f| %>
        <div class="modal-body">
          <div class="mb-3">
            <%= f.label :aquarium_introduction, class: "col-form-label", for: "message-text" %>
            <%= f.text_area :aquarium_introduction, class: "form-control", id: "message-text", size: "30x5" %>
          </div>
          <div class="mb-3">
            <%= f.label :aquarium_image, class: "col-form-label" %>
            <%= f.file_field :aquarium_image, class: "form-control" %>
          </div>
            <%= f.hidden_field :user_id, value: current_user.id %>
        </div> 
        <div class="modal-footer">
        <%= f.submit "投稿する", class: "btn btn-primary mb-3" %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/aquaria/_posts.html.erb
<div class="posts-box d-none d-lg-block shadow p-3 mb-5 bg-white rounded">
  <div class="row">
    <%= link_to detail_path(aquarium.user.id), class: "col-lg-1 col-sm-1" do %>
      <% if aquarium.user.user_image? %>
        <%= image_tag(aquarium.user.user_image.to_s, alt: "user-icon", size: "70", class: "host-icon") %>
      <% else %>
        <%= image_tag("default_user.jpeg", alt: "user-icon", size: "70", class: "host-icon") %>
      <% end %>
    <% end %>
    <div class="col-lg-7 col-sm-6 ms-2">
      <span>
        <%= link_to aquarium.user.name, detail_path(aquarium.user.id), class: "user-name" %>
      </span>
      <br>
      <p class="time-stamp">
        <%= "#{time_ago_in_words(aquarium.created_at)}前に投稿" %>
      </p>
      <p class="introduction pt-2">
        <%= aquarium.aquarium_introduction %>
      </p>
      <div class="likes-buttons" id="likesButtons-<%= aquarium.id %>">
        <%= render partial: "likes/like", locals: { aquarium: aquarium } %>
      </div>

      <div class="comment-count">
        <%= link_to aquarium_path(aquarium, anchor: "comment-form"), class: "comment-link" do %>
          <span class="far fa-comment-dots"></span>
        <% end %>
        <%= aquarium.comments.count %>
      </div>
    </div>
    
    <div class="col-lg-3 col-sm-12">
      <%= link_to aquarium_path(aquarium) do %>
        <% if aquarium.persisted? && aquarium.aquarium_image? %>
          <%= image_tag(aquarium.aquarium_image.to_s, alt: "aquarium_image", class: "img-thumbnail img-hover") %>
        <% else %>
          <%= image_tag("no_image.jpg", alt: "aquarium_image", class: "img-thumbnail img-hover") %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="d-lg-none">
  <div class="posts-sp-box shadow p-3 mb-5 bg-white rounded">
    <div class="row">
      <%= link_to detail_path(aquarium.user.id), class: "col-lg-1 col-sm-1" do %>
        <% if aquarium.user.user_image? %>
          <%= image_tag(aquarium.user.user_image.to_s, alt: "user-icon", size: "70", class: "host-icon") %>
        <% else %>
          <%= image_tag("default_user.jpeg", alt: "user-icon", size: "70", class: "host-icon") %>
        <% end %>
      <% end %>
      <div class="col-6">
        <p class="user-name">
          <%= link_to aquarium.user.name, detail_path(aquarium.user.id) %>
        </p>
        <br>
        <p class="time-stamp">
          <%= "#{time_ago_in_words(aquarium.created_at)}前に投稿" %>
        </p>
      </div>
    </div>
    <div class="row">
      <p class="introduction">
        <%= aquarium.aquarium_introduction %>
      </p>
      <div class="like-comment">
        <div class="likes-buttons" id="likesButtons-sp-<%= aquarium.id %>">
          <%= render partial: "likes/like", locals: {aquarium: aquarium} %>
        </div>

        <div class="comment-count mb-2">
          <%= link_to aquarium_path(aquarium, anchor: "comment-form"), class: "comment-link" do %>
            <span class="far fa-comment-dots"></span>
            <%= aquarium.comments.count %>
          <% end %>
        </div>
      </div>
    </div>
    <%= link_to aquarium_path(aquarium) do %>
      <% if aquarium.persisted? && aquarium.aquarium_image? %>
        <%= image_tag(aquarium.aquarium_image.to_s, alt: "aquarium_image", class: "img-thumbnail") %>
      <% else %>
        <%= image_tag("no_image.jpg", alt: "aquarium_image", class: "img-thumbnail") %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/aquaria/_search_field.html.erb
<%= search_form_for q, url: url do |f| %>
  <div class="search-field">
    <%= f.search_field :aquarium_introduction_cont, class: "form-control", placeholder: '投稿検索', id: 'aquarium-search' %>
    <i class="fas fa-search"></i>
  </div>
  <%= f.submit class: "d-none" %>
<% end %>

app/views/aquaria/create.js.erb
<% if @status == "fail" %>
  $("#new-modal-error").html("<ul><% @aquarium.errors.full_messages.each do |message| %><li><%= message %></li><% end %></ul>")
<% end %>

app/views/aquaria/edit.js.erb
$("#editModal").html("<%= escape_javascript(render 'aquaria/edit_modal') %>");
$("#editModal").modal("show");

app/views/aquaria/index.html.erb
<%= provide(:title, "投稿一覧") %>

<div class="modal fade" id="new-modal" tabindex="-1" aria-hidden="true", role="dialog"></div>
<div class="container py-4">
  <div class="row">
    <%= render "navbar" %>
    <div class="p-4 bg-color">
      <div class="row">
        <%= render partial: "posts", collection: @aquaria, as: "aquarium" %>
      </div>
    </div>
  </div>
</div>
<%= paginate @aquaria %>

app/views/aquaria/new.js.erb
$("#new-modal").html("<%= escape_javascript(render 'aquaria/new_modal') %>");
$("#new-modal").modal("show");

app/views/aquaria/search.html.erb
<div class="container">
  <h4 class="mt-5 mb-3">検索結果: <%= @count %>件</h4>
  <div class="row">
    <% @results.each do |aquarium| %>
      <div class="search-aquarium-box col-sm-6 col-lg-4 col-xl-3">
        <div class="search-aquarium-inner shadow-sm p-3 mb-5 bg-white rounded">
          <%= link_to aquarium_path(aquarium) do %>
            <div class="aquarium-image-out">
              <% if aquarium.persisted? && aquarium.aquarium_image? %>
                <%= image_tag(aquarium.aquarium_image.to_s, alt: "aquarium-image", class: "aquarium-image") %>
              <% else %>
                <%= image_tag("no_image.jpg", alt: "aquarium-image", class: "img-thumbnail") %>
              <% end %>
            </div>
          <% end %>
          <p class="time-stamp">
              <%= "#{time_ago_in_words(aquarium.created_at)}前に投稿" %>
          </p>
          <%= aquarium.aquarium_introduction %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= paginate @results %>

app/views/aquaria/show.html.erb
<%= provide(:title, "投稿詳細ページ") %>
<div class="modal fade" id="editModal" tabindex="-1" aria-hidden="true", role="dialog"></div>
<%= render partial: "likes/like_modal", locals: { liked_users: @liked_users } %>

<div class="main-content my-4">
  <div class="container">
    <div class="bg-color show-box shadow p-3 mb-5 bg-white rounded">
      <div class="bg-dark">
        <div class="aquaria-image mb-4">
          <% if @aquarium.persisted? && @aquarium.aquarium_image? %>
            <%= image_tag(@aquarium.aquarium_image.to_s, alt: "aquarium_image", class: "img-thumbnail") %>
          <% else %>
            <%= image_tag("no_image.jpg", alt: "aquarium_image", class: "img-thumbnail") %>
          <% end %>
        </div>
      </div>

      <div class="p-4 ms-1 d-none d-md-block">
        <div class="row">
          <%= link_to image_tag(@aquarium.user.user_image.to_s, alt: "user-icon", class: "host-icon"), detail_path(@aquarium.user.id), class: "col-lg-1 col-sm-1" %>
          <div class="col-lg-7 col-sm-6 ms-5">
            <span>
              <%= link_to @aquarium.user.name, detail_path(@aquarium.user.id),  class: "user-name" %>
            </span>
            <br>
            <p class="time-stamp">
              <%= "#{time_ago_in_words(@aquarium.created_at)}前に投稿" %>
            </p>
            <p class="introduction pt-2">
              <%= @aquarium.aquarium_introduction %>
            </p>
            <div class="row">
              <div class="col-lg-8">
                <% if current_user.already_liked?(@aquarium) %>
                  <%= link_to aquarium_likes_path(@aquarium), method: "delete" do %>
                    <span class="fas fa-heart like-btn"></span>
                  <% end %>
                <% else %>
                  <%= link_to aquarium_likes_path(@aquarium), method: "post" do %>
                    <span class="fas fa-heart unlike-btn"></span>
                  <% end %>
                <% end %>
                <span class="likes-count"><%= @aquarium.likes.count %></span>

                <% if @aquarium.likes.count > 0 %>
                  <span class="like-user">
                    <%= link_to "いいねしたユーザー", "#", "data-bs-toggle": :"modal", "role": :"button", "data-bs-target": :"#likeModal" %>
                  </span>
                <% end %>
              </div>

              <% if @aquarium.user.id == current_user.id%>
                <div class="col-lg-4 text-end">
                  <%= link_to edit_aquarium_path, remote: true, class: "me-2 text-success", id: "edit-button" do %>
                    <i class="fas fa-edit"></i>
                  <% end %>
                  <%= link_to aquarium_path(@aquarium), method: :delete, :data => {:confirm => '本当に削除しますか?'}, class: "text-danger", id: "delete-button" do %>
                    <i class="fas fa-trash-alt"></i>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="d-md-none">
        <div class="row">
          <%= link_to image_tag(@aquarium.user.user_image.to_s, alt: "user-icon", size: "70", class: "host-icon"), detail_path(@aquarium.user.id), class: "col-sm-2 col-3" %>
          <div class="col-6">
            <p class="user-name">
              <%= link_to @aquarium.user.name, detail_path(@aquarium.user.id) %>
            </p>
            <br>
            <p class="time-stamp">
              <%= "#{time_ago_in_words(@aquarium.created_at)}前に投稿" %>
            </p>
          </div>
        </div>
        <div class="row">
          <p class="introduction">
            <%= @aquarium.aquarium_introduction %>
          </p>
          
          <div class="likes-buttons" id="likesButtons-sp-<%= @aquarium.id %>">
            <% if current_user.already_liked?(@aquarium) %>
              <%= link_to aquarium_likes_path(@aquarium), method: "delete" do %>
                <span class="fas fa-heart like-btn"></span>
              <% end %>
            <% else %>
              <%= link_to aquarium_likes_path(@aquarium), method: "post" do %>
                <span class="fas fa-heart unlike-btn"></span>
              <% end %>
            <% end %>
            <span class="likes-count"><%= @aquarium.likes.count %></span>
            <% if @aquarium.likes.count > 0 %>
              <span class="like-user">
                <%= link_to "いいねしたユーザー", "#", "data-bs-toggle": :"modal", "role": :"button", "data-bs-target": :"#likeModal" %>
              </span>
            <% end %>
          </div>

          <% if @aquarium.user.id == current_user.id%>
            <div class="col-lg-4 text-end">
              <%= link_to edit_aquarium_path, remote: true, class: "me-2 text-success", id: "edit-button" do %>
                <i class="fas fa-edit"></i>
              <% end %>
              <%= link_to aquarium_path(@aquarium), method: :delete, :data => {:confirm => '本当に削除しますか?'}, class: "text-danger", id: "delete-button" do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="border-bottom"></div>
      <div class="container mt-3">
        <div id="comment-form">
          <%= render partial: "comments/comment_form", locals: { aquarium: @aquarium, comment: @comment }  %>
        </div>
        <div class="row">
          <ul id="comments-area">
            <li>
              <%= render partial: "comments/index", locals: { comments: @comments, aquarium: @aquarium } %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/aquaria/update.js.erb
<% if @status == "fail" %>
  $("#edit-modal-error").html("<ul><% @aquarium.errors.full_messages.each do |message| %><li><%= message %></li><% end %></ul>")
<% end %>