config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :mailer => 'users/mailer'
  } 

  devise_scope :user do
    get 'users/:id/posts' => 'users/registrations#user_posts', as: 'users_posts'
    get 'users/:id/liked_aquaria' => 'users/registrations#liked_aquaria', as: 'users_liked_aquaria'
    post 'users/guest_sign_in' => 'users/sessions#new_guest'
    get 'sign_up' => 'users/registrations#new'
    get 'log_in' => 'users/sessions#new'
    get 'log_out' => 'users/sessions#destroy'
    get 'users/:id/detail' => 'users/registrations#detail', as: 'detail'
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  root 'home#top'
  get '/' => 'home#top'
  resources :aquaria do
    collection do
      get 'search'
    end
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :maps, only: :index
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :aquaria, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_aquaria, through: :likes, source: :aquarium

  has_many :comments, dependent: :destroy

  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'following_id'
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'follower_id'
  has_many :followers, through: :passive_relationships, source: :following

  mount_uploader :user_image, UserImageUploader
  mount_uploader :profile_image, UserImageUploader

  validates :name, presence: true
  validates :introduction, length: { maximum: 140 }

  def aquaria
    Aquarium.where(user_id: id)
  end

  def already_liked?(aquarium)
    likes.exists?(aquarium_id: aquarium.id)
  end

  def follow(user)
    active_relationships.create!(follower_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(follower_id: user.id).destroy
  end

  def followed_by?(user)
    # 今自分(引数のuser)がフォローしようとしているユーザーがフォローされているユーザー(passive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    passive_relationships.find_by(following_id: user.id).present?
  end
end

app/controllers/users/mailer.rb
class Users::Mailer < Devise::Mailer
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :check_guest, only: :destroy
  def check_guest
    if resource.email == 'test@com'
      redirect_to aquaria_path, alert: 'テストユーザーは削除できません。'
    end
  end

  def user_posts
    @user = User.find(params[:id])
    @aquarium = Aquarium.new
    @aquaria = @user.aquaria.order(created_at: :desc).page(params[:page]).per(15)
  end

  def liked_aquaria
    @user = User.find(params[:id])
    @liked_aquaria = @user.liked_aquaria.order(created_at: :desc).page(params[:page]).per(15)
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # # POST /resource
  # def create
  #   super
  # end

  # # GET /resource/edit
  # def edit
  #   super
  # end

  # # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroys
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  def detail
    @user = User.find_by(id: params[:id])
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    "/users/#{current_user.id}/detail"
  end

  def after_update_path_for(resource)
    "/users/#{current_user.id}/detail"
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def new_guest
    @user = User.find_or_create_by!(name: "テストユーザー", email: "test@com", user_image: nil) do |user|
      user.password = SecureRandom.urlsafe_base64
    end
    sign_in @user
    redirect_to aquaria_path, notice: "テストユーザーとしてログインしました。"
  end
  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def follows
    @user = User.find(params[:id])
    @users = @user.followings.order(created_at: :desc).page(params[:page]).per(15)
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers.order(created_at: :desc).page(params[:page]).per(15)
  end
end

app/views/users/_follow_btn.html.erb
<% if current_user != user %>
  <% if user.followed_by?(current_user) %>
    <%= link_to user_relationships_path(user.id), method: :delete, class: "btn follow-btn unfollow", remote: :true do %>
      <span>フォロー中</span>
    <% end %>
  <% else %>
    <%= link_to user_relationships_path(user.id), method: :post, class: "btn follow-btn follow", remote: :true do %>
      <i class="fas fa-plus"></i>
      <span>フォロー</span>
    <% end %>
  <% end %>
<% else %>
  <p>マイアカウント</p>
<% end %>

app/views/users/_followers.html.erb
<div class="container user pb-4 ">
  <div class="bg-color shadow p-3 mb-5 bg-white rounded">
    <ul class="follow-list">
      <div class="row">
        <% users.each do |user| %>
          <li class="followers-box col-lg-4 shadow-sm p-3 mb-5 rounded">
            <div class="row">
              <article class="col-sm-2">
                <%= link_to detail_path(user.id), class: "col-lg-1 col-sm-1" do %>
                  <% if user.user_image? %>
                    <%= image_tag(user.user_image.to_s, alt: "user-icon", size: "70", class: "host-icon follow-icon") %>
                  <% else %>
                    <%= image_tag("default_user.jpeg", alt: "user-icon", size: "70", class: "host-icon follow-icon") %>
                  <% end %>
                <% end %>
              </article>
              <article class="col-sm-6 ms-1">
                <p><%= link_to user.name, detail_path(user.id) %></p>
                <p class="self-introduction"><%= user.introduction %></p>
              </article>
              <article class="follow-list-btn" id="followerListBtn-<%= user.id %>">
                <%= render partial: "users/follow_btn", locals: { user: user } %>
              </article>
            </div>
          </li>
        <% end %>
      </div>
    </ul>
  </div>
</div>
<%= paginate users, remote: true %>

app/views/users/_followers_count.html.erb
<%= user.followers.count %>

app/views/users/_follows.html.erb
<div class="container user pb-4 ">
  <div class="bg-color shadow p-3 mb-5 bg-white rounded">
    <ul class="follow-list">
      <div class="row">
        <% users.each do |user| %>
          <li class="follows-box col-lg-4 shadow-sm p-3 mb-5 rounded">
            <div class="row">
              <article class="col-sm-2">
                <%= link_to detail_path(user.id), class: "col-lg-1 col-sm-1" do %>
                  <% if user.user_image? %>
                    <%= image_tag(user.user_image.to_s, alt: "user-icon", size: "70", class: "host-icon follow-icon") %>
                  <% else %>
                    <%= image_tag("default_user.jpeg", alt: "user-icon", size: "70", class: "host-icon follow-icon") %>
                  <% end %>
                <% end %>
              </article>
              <article class="col-sm-6 ms-1">
                <p><%= link_to user.name, detail_path(user.id) %></p>
                <p class="self-introduction"><%= user.introduction %></p>
              </article>
              <article class="follow-list-btn" id="followListBtn-<%= user.id %>">
                <%= render partial: "users/follow_btn", locals: { user: user } %>
              </article>
            </div>
          </li>
        <% end %>
      </div>
    </ul>
  </div>
</div>
<%= paginate users, remote: true %>

app/views/users/_follows_count.html.erb
<%= user.followings.count %>

app/views/users/followers.html.erb
<%= provide(:title, "フォロワー") %>

<div class="container user py-4 ">
  <%= render "users/registrations/users_navbar" %>
  <div class="bg-color shadow p-3 mb-5 bg-white rounded">
    <ul class="follow-list">
      <div class="row">
        <% @users.each do |user| %>
          <li class="col-lg-4 shadow-sm p-3 mb-5 rounded">
            <div class="row">
              <article class="col-sm-2">
                <%= link_to image_tag(user.user_image.to_s, alt: "user-icon", class: "host-icon follow-icon"), users_posts_path(user.id) %>
              </article>
              <article class="col-sm-6 ms-1">
                <p><%= link_to user.name, users_posts_path(user.id) %></p>
                <p class="self-introduction"><%= user.introduction %></p>
              </article>
              <article class="follow-list-btn" id="followerListBtn-<%= user.id %>">
                <%= render partial: "users/follow_btn", locals: { user: user } %>
              </article>
            </div>
          </li>
        <% end %>
      </div>
    </ul>
  </div>
</div>

app/views/users/followers.js.erb
$('#detailContents').html("<%= j(render partial: 'users/followers', locals: { users: @users }) %>");

app/views/users/follows.html.erb
<%= provide(:title, "フォロー") %>

<div class="container user py-4 ">
  <%= render "users/registrations/users_navbar" %>
  <div class="bg-color shadow p-3 mb-5 bg-white rounded">
    <ul class="follow-list">
      <div class="row">
        <% @users.each do |user| %>
          <li class="col-lg-4 shadow-sm p-3 mb-5 rounded">
            <div class="row">
              <article class="col-sm-2">
                <%= link_to image_tag(user.user_image.to_s, alt: "user-icon", class: "host-icon follow-icon"), users_posts_path(user.id) %>
              </article>
              <article class="col-sm-6 ms-1">
                <p><%= link_to user.name, users_posts_path(user.id) %></p>
                <p class="self-introduction"><%= user.introduction %></p>
              </article>
              <article class="follow-list-btn" id="followListBtn-<%= user.id %>">
                <%= render partial: "users/follow_btn", locals: { user: user } %>
              </article>
            </div>
          </li>
        <% end %>
      </div>
    </ul>
  </div>
</div>

app/views/users/follows.js.erb
$('#detailContents').html("<%= j(render partial: 'users/follows', locals: { users: @users }) %>");