config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :mailer => 'users/mailer'
  } 

  devise_scope :user do
    get 'users/:id/posts' => 'users/registrations#user_posts', as: 'users_posts'
    get 'users/:id/liked_aquaria' => 'users/registrations#liked_aquaria', as: 'users_liked_aquaria'
    post 'users/guest_sign_in' => 'users/sessions#new_guest'
    get 'sign_up' => 'users/registrations#new'
    get 'log_in' => 'users/sessions#new'
    get 'log_out' => 'users/sessions#destroy'
    get 'users/:id/detail' => 'users/registrations#detail', as: 'detail'
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  root 'home#top'
  get '/' => 'home#top'
  resources :aquaria do
    collection do
      get 'search'
    end
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :maps, only: :index
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="text-center p-3 my-5 fs-3", style="background-color: #222;">
  <p class="text-light"><i class="fas fa-fish"></i>Aquarist</p>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand ms-2 me-5" do %>
      <p class="mb-0 fs-3 logo"><i class="fas fa-fish"></i>Aquarist</p>
    <% end %>
    <% if user_signed_in? %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" id="hamburger">
        <i class="fas fa-bars" style="color: #fff; font-size: 30px;"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto fs-4">
          <li class="nav-item search-link">
            <%= link_to "ショップ検索", maps_path, class: "nav-link me-4" %>
          </li>
          <div class="d-lg-block d-none">
            <li class="nav-item dropdown" id="current_user">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <% if current_user.user_image? %>
                <%= image_tag(current_user.user_image.to_s, alt: "user_image", class: "host-icon") %>
              <% else %>
                <%= image_tag("default_user.jpeg", alt: "user_image", class: "host-icon") %>
              <% end %>
              <%= current_user.name %>
              </a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <li><%= link_to "アカウント", detail_path(current_user.id), class: "dropdown-item" %></li>
                  <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
                </ul>
            </li>
          </div>
          <div class="d-lg-none">
            <li class="nav-item"><%= link_to "アカウント", detail_path(current_user.id), class: "nav-account-item" %></li>
            <li class="nav-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-account-item" %></li>
          </div>
        </ul>
      </div>
    <% else %>
      <% if current_page?("/") %>
        <%= link_to "Aquaristとは?", "#about", class: "navbar-brand d-none d-lg-block" %>
      <% end %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" id="hamburger">
        <i class="fas fa-bars" style="color: #fff; font-size: 30px;"></i>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav fs-4">
          <li class="nav-item me-4">
            <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item me-3">
            <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/_top_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand ms-2 me-4" do %>
      <p class="mb-0 fs-3 logo"><i class="fas fa-fish"></i>Aquarist</p>
    <% end %>
    <%= link_to "Aquaristとは?", "#about", class: "navbar-brand d-none d-lg-block" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" id="hamburger">
      <i class="fas fa-bars" style="color: #fff; font-size: 30px;"></i>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav fs-4">
        <li class="nav-item me-4">
          <%= link_to "Log in", "#", class: "nav-link" %>
        </li>
        <li class="nav-item me-3">
          <%= link_to "新規登録", "#", class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> 
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.ico') %>
    <!-- css -->
    <%= stylesheet_link_tag 'https://use.fontawesome.com/releases/v5.6.1/css/all.css', rel: 'stylesheet' %>
    <%= stylesheet_link_tag  'reboot.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- javascript -->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 
  </head>
  <body>
    <main>
      <%= render "layouts/header" %>
      <%= render "layouts/flash" %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </main>
  </body>
</html>